version: '3.7'

services:
    database:
        image: 'mongo'
        container_name: 'mongo'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: sprint-retrospective
            MONGO_DATA_DIR: /var/lib/mongodb
        volumes:
            - data-mongo:/var/lib/mongodb
        restart: always

    redis:
        image: 'redis'
        container_name: 'redis'
        restart: always
        ports:
            - "6379:6379"

    message-queue:
        image: 'softwaremill/elasticmq'
        container_name: 'message-queue'
        ports:
            - "9324:9324"
        restart: always

    api:
        build: https://github.com/RobinJ1995/sprint-retrospective-server.git
        image: robinj/sprintretrospective-api
        ports:
            - 5432:5432
        environment:
            DB_HOST: 'mongo'
            SQS_QUEUE_NAME: 'events'
            SQS_ENDPOINT: 'message-queue:9324'
        depends_on:
            - database
            - redis
            - message-queue
        restart: always

    frontend:
        build:
            context: https://github.com/RobinJ1995/sprint-retrospective.git
            args:
                API_ENDPOINT: 'http://localhost:5432'
        image: robinj/sprintretrospective-frontend
        ports:
            - 5431:80
        restart: always

volumes:
    data-mongo:
